services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodleuser
      - MOODLE_DATABASE_PASSWORD=moodlepassword
    volumes:
      - ./moodledata:/var/www/moodledata
    restart: always 

  cron:
    image: php:8.1-cli
    depends_on:
      - moodle
    volumes:
      - .:/var/www/html
    entrypoint: ["sh", "-c", "while true; do /usr/local/bin/php /var/www/html/admin/cli/cron.php; sleep 60; done"]


  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodleuser
      POSTGRES_PASSWORD: moodlepassword
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8081:80"  # Cambia el puerto aquí
    depends_on:
      - db

volumes:
  db_data:
    driver: local
  moodledata:
    driver: local
